#pastikan terminal berada di directory project dan file ini kemudian file ini diberinama "docker-compose.yaml"
version: "3.7" #versi docker compose yang digunakan

services:
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        ports:
            - 207017:207017
        networks:
            - java_network
    redis:
        container_name: redis
        image: redis:5
        ports:
            - 6379:6379
        networks:
            - java_network
    java-docker:
        container_name: java-docker
        image: java-docker:1.0
        ports:
            - 8080:8080
        depends_on: #memberi tahu bahwa container ini membutuhkan container lain yaitu redis dan mongo
            - redis
            - mongo
        environment:
            - NAME=DOCKER
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        networks:
            - java_network

networks:
    java_network:
        name: java_network